<a href="https://colab.research.google.com/github/priyeshr7/Data-Science/blob/main/Untitled2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])
print(a
      )

[1 2 3 4]


In [5]:
b = np.array(([1,2,3,4],[2,3,4,5]))
print(b)

[[1 2 3 4]
 [2 3 4 5]]


In [6]:
np.array(([1,2,3,4],[2,3,4,5]),dtype=bool)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [7]:
np.array(([1,2,3,4],[2,3,4,5]),dtype=float)

array([[1., 2., 3., 4.],
       [2., 3., 4., 5.]])

In [9]:
#np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [14]:
#reshape
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
#np.ones ad np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
np.random.random((2,3))

array([[0.23709752, 0.40790579, 0.78997656],
       [0.6849688 , 0.93871652, 0.1557145 ]])

In [18]:
# generate equally spaced number in a range
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [19]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
p1= np.arange(10)
p2=np.arange(12,dtype=float).reshape(3,4)
p3=np.arange(8).reshape(2,2,2)
p3


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [25]:
#ndim
p3.ndim

3

In [26]:
#shape
p2.shape

(3, 4)

In [30]:
#size
print(p3.size)

8


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [31]:
# itemsize
p3.itemsize

8

In [32]:
# dtype
p1.dtype

dtype('int64')

In [33]:
# astype to change datatype of array
p1.astype(np.float32)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

# Array Operation


In [34]:
a2= np.arange(12).reshape(3,4)
b2= np.arange(12,24).reshape(3,4)

In [35]:
# scalar operation
a2 **2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [36]:
a2 >5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [37]:
a2== 5


array([[False, False, False, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [40]:
# vector operation
a2 + b2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

# Array Function

In [5]:
 a3 = np.random.random((3,3))
 a3 = np.round(a3*100)
 a3

array([[28.,  9.,  8.],
       [14., 18., 71.],
       [83., 31., 22.]])

In [7]:
np.max(a3)

83.0

In [8]:
np.min(a3)

8.0

In [9]:
np.prod(a3)

2041793816832.0

In [10]:
np.sum(a3)

284.0

In [11]:
#column
np.sum(a3,axis=0)

array([125.,  58., 101.])

In [12]:
#row
np.sum(a3,axis=1)

array([ 45., 103., 136.])

In [13]:
np.median(a3)

22.0

In [15]:
np.mean(a3)

31.555555555555557

In [18]:
np.std(a3,axis=1)

array([ 9.20144916, 25.97862369, 26.88659311])

In [17]:
np.var(a3)

651.3580246913581

In [20]:
a2 = np.arange(12).reshape(3,4)
a4 = np.arange(12,24).reshape(4,3)
np.dot(a2,a4)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [22]:
np.log(a2)

<ipython-input-22-e0fbf9947be5>:1: RuntimeWarning: divide by zero encountered in log
  np.log(a2)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [24]:
np.exp(a2)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [27]:
# round / floor / ceil
np.round(np.random.random((2,3))*100)

array([[51., 26.,  8.],
       [42., 78.,  3.]])

# Indexing and Slicing

In [28]:
a1= np.arange(10)
a2= np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [32]:
a1[-1]

9

In [33]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
a2[1,2]

6

In [35]:
# [row,col]
a2[2,3]

11

In [36]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [37]:
a3[1,0,1]

5

In [38]:
#[matrix,row,col]
a3[1,0,0]

4

In [41]:
a3[0,1,0]

2

In [43]:
#slicing
a1[2:5:2]

array([2, 4])

In [44]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
a2[0,:]

array([0, 1, 2, 3])

In [47]:
a2[2,:]

array([ 8,  9, 10, 11])

In [49]:
a2[2,[1,2]]

array([ 9, 10])

In [50]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [51]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [60]:
1,3
9, 11
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [61]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [71]:
4 , 7
a2[1,::3]

array([4, 7])

In [73]:
1,2 ,3
5,6,7
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [75]:
a3 =np.arange(27).reshape(3,3,3)

In [76]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [77]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [78]:
a3[0,1,:]

array([3, 4, 5])

In [79]:
a3[1,:,1]

array([10, 13, 16])

In [80]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [81]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [85]:
a1
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [86]:
a2
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [87]:
a3
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [88]:
# nditer print all the element of any dimention of matrix one by one
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [89]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [90]:
# Transpose
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [91]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [92]:
#ravel
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [93]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [95]:
# Horizontal Stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)


array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [96]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [97]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [103]:
a6=np.hstack((a4,a5))

In [99]:
# Vertical Stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [100]:
np.vstack((a4,a5,a4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# Splitting


In [109]:
# horizontal Splitting
np.hsplit(a6,2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [111]:
np.hsplit(a6,4)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]]),
 array([[12, 13],
        [16, 17],
        [20, 21]]),
 array([[14, 15],
        [18, 19],
        [22, 23]])]

In [113]:
# Vertical Splitting
np.vsplit(a6,3)

[array([[ 0,  1,  2,  3, 12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7, 16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11, 20, 21, 22, 23]])]